### ISSUE TITLE
Use strict: not found [v2.0.0] 

### ISSUE THREAD

**Issue by simon-nowak** [GridexX/sarif-codeclimate#2]
Hello,

since the 2.0.0 update we are facing an issue in our CI
>/.../node_modules/.bin/sarif-codeclimate: 1: use strict: not found
>/.../node_modules/.bin/sarif-codeclimate: 2: Syntax error: word unexpected (expecting ")")

or localy
>//.../node_modules/.bin/sarif-codeclimate: line 1: use strict: command not found
>//.../node_modules/.bin/sarif-codeclimate: line 2: syntax error near unexpected token 'exports,'
>//.../node_modules/.bin/sarif-codeclimate: line 2: Object.defineProperty(exports, "__esModule", { value: true });'

The command that we run:
`sarif-codeclimate --input relativePathLocation.json --output gl-code-quality-report.json`

Is there anything we need to do in our package.json file?

**Comment by GridexX** [comment]
the destination of the files have been changed as the package was re-written in typescript.
You could check the Readme for usage or set the version to '1.0.2' in your package.json to keep the same behavior

Hope it will help !

**Comment by GridexX** [comment]
Fixed in version `2.0.1` @simon-nowak !

**Comment by simon-nowak** [comment]
Thank you !!

I confirm the last version is now working. I will do some test and update the other open issue accordngly.
