### ISSUE TITLE
version number does not match

### ISSUE THREAD

**Issue by Dubhar** [GridexX/sarif-codeclimate#5]
When asking the package for it's version it answers with a wrong number, i.e.
```bash
# npx -y sarif-codeclimate@2.1.2 --version
2.0.0
```
I'd probably just remove the version in `src/bin/sarif-codeclimate.ts:12` so I don't have to remember updating the line when releasing a new version.

**Comment by GridexX** [comment]
Hello @Dubhar Good catch :+1: !

Indeed, the version could be extracted from the `package.json` field. 

Would you like to contribute to this project by opening a MR ?

It would be very helpful and I can help you with the dev
